In [1]:
import pandas as pd

df=pd.read_pickle('data.allpoems.pkl')

def filter_poem_txt(txt):
    vparas = [para.strip() for para in txt.split('\n\n') if '\n' in para.strip()]
    return '\n\n'.join(vparas)

def num_lines_txt(txt):
    return len([v for v in txt.splitlines() if v.strip()])

df['poem_txt'] = df['poem'].apply(filter_poem_txt)
df['num_lines_txt'] = df['poem_txt'].apply(num_lines_txt)

In [2]:
df[['poem_txt','num_lines_txt']]

                                                poem_txt  num_lines_txt
0      In the heart of the bustling city,\nThere lies...             30
1      In the stillness of the night\nI lay awake, co...             28
2      among\nthe c\nr\ne\na\ns\nes\n\nof the\nfa\nl\...             21
3      In the depths of the forest, where shadows dan...             40
4      Alas, what fate doth bring me to this pass? \n...             15
...                                                  ...            ...
67310  Talk in your sleep of Lilith,\nAnd say that sh...             20
67312  Two days of mossy mists,\nsoft & clinging. The...             29
67313  O! Molly Bawn, why leave me pining,\n    All l...             18
67315  Love put his bow into my hand,\n        Charg'...             18
67316  Vertue's a Babe, first born in Paradise,\nAnd ...             22

[68769 rows x 2 columns]

In [3]:
df[df['prompt'].fillna('').str.contains('sonnet')][['num_lines','num_lines_txt', 'poem_txt']].query('num_lines == 14')

,num_lines,num_lines_txt,poem_txt
12,14,14,When spring's first blossoms fill the air with...
24,14,14,When winter's chill doth pierce the weary soul...
69,14,14,When spring's fair blossoms grace the verdant ...
79,14,14,"When golden sunbeams filter through the trees,..."
84,14,14,"When autumn's chill pervades the fading light,..."
...,...,...,...
2941,14,14,"Upon the hill where roses bloom so fair,\nI sa..."
2949,14,14,When autumn's chill doth pierce the morning ai...
2981,14,14,"When summer's bloom has faded from the land,\n..."
3005,14,14,"Oh, how my heart doth ache with love so true,\..."
3030,14,14,When springtime blossoms fill the air with mir...

In [4]:
import sys
sys.path.insert(0,'..')
sys.path.insert(0,'/Users/ryan/github/prosodic')
# !pip install -r /Users/ryan/github/prosodic/requirements.txt

import prosodic

shaksonnets = prosodic.Text(fn='/Users/ryan/github/prosodic/corpora/corppoetry_en/en.shakespeare.txt')

In [5]:
constraints={
    'w_peak':3.0,
    'w_stress':1.0,
    's_unstress':1.0,
    'unres_across':1.0,
    'unres_within':1.0,
    'pentameter':10.0,
}
meter = prosodic.Meter(
    constraints=constraints,
    resolve_optionality=True,
    max_s=1,
    max_w=2,
)

parses = shaksonnets.parse(meter=meter)

[7.42s] Parsing lineparts [8x]: 100%|█████████▉| 3065/3071 [00:52<00:00, 76.80it/s]